config/routes.rb
Rails.application.routes.draw do
  root 'dashboard#index'

  # Devise
  devise_for :users, skip: [:registrations]

  # Users
  get 'users/account', to: 'users#account'

  # Dashboard
  resources :dashboard, only: %i[index]

  # Thoughts
  get 'thoughts/favorites', to: 'thoughts#favorites'
  patch 'thoughts/:id/bookmark', to: 'thoughts#bookmark'
  patch 'thoughts/:id/unbookmark', to: 'thoughts#unbookmark'
  delete 'thoughts/all', to: 'thoughts#destroy_all'
  resources :thoughts, only: %i[index new edit create destroy update]

  # Recoveries
  get 'recoveries/favorites', to: 'recoveries#favorites'
  delete 'recoveries/all', to: 'recoveries#destroy_all'
  resources :recoveries
  patch 'recoveries/:id/report', to: 'recoveries#submit_report'
  get 'recoveries/:id/renew', to: 'recoveries#renew'
  patch 'recoveries/:id/renew', to: 'recoveries#submit_renew'
  patch 'recoveries/:id/bookmark', to: 'recoveries#bookmark'
  patch 'recoveries/:id/unbookmark', to: 'recoveries#unbookmark'

  # Stoppers
  resources :recoveries do
    resources :stoppers, only: %i[index new create]
  end

  # Routines
  get 'routines/favorites', to: 'routines#favorites'
  delete 'routines/all', to: 'routines#destroy_all'
  resources :routines
  patch 'routines/:id/report', to: 'routines#submit_report'
  patch 'routines/:id/setback', to: 'routines#submit_setback'
  patch 'routines/:id/bookmark', to: 'routines#bookmark'
  patch 'routines/:id/unbookmark', to: 'routines#unbookmark'
  get 'routines/:id/new_target', to: 'routines#new_target'
  patch 'routines/:id/submit_new_target', to: 'routines#submit_new_target'

  # Reminders
  delete 'reminders/all', to: 'reminders#destroy_all'
  resources :reminders

  # Budgets
  resources :budgets

  # Expenses
  resources :budgets do
    resources :expenses, except: %i[index]
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @random_reminder = current_user.reminders.order('RANDOM()').first
    @reminders_count = current_user.reminders.count
    @thoughts_count = current_user.thoughts.count
    @recoveries_count = current_user.recoveries.count
    @routines_count = current_user.routines.count
    @budgets_count = current_user.budgets.count
  end
end

app/views/dashboard/_budgets_count.html.haml
= link_to budgets_path, title: "Budgets" do
  %article.px-3.py-2.rounded-md.border.border-2.border-neutral-300.bg-white.hover:bg-neutral-50.hover:border-neutral-500
    .flex.justify-between.items-center.px-3
      .flex.items-center
        = image_tag "bills.svg", alt: "bills", class: "w-6 mr-3"
        %h3.text-xl.font-bold Budgets
      %p.text-3xl.text-blue-500.font-bold.number= budgets_count

app/views/dashboard/_expense_lists_count.html.haml
= link_to expense_lists_path, title: "Expense lists" do
  %article.px-3.py-2.rounded-md.border.border-2.border-neutral-300.bg-white.hover:bg-neutral-50.hover:border-neutral-500
    .flex.justify-between.items-center.px-3
      .flex.items-center
        = image_tag "bills.svg", alt: "bills", class: "w-6 mr-3"
        %h3.text-xl.font-bold Expense lists
      %p.text-3xl.text-blue-500.font-bold.number= expense_lists_count

app/views/dashboard/_random_reminder.html.haml
.px-3.py-2.bg-neutral-100.rounded-md.border.border-neutral-300
  %h3.mb-1.italic.text-neutral-500 Reminder:
  %p.break-words.text-neutral-600.font-semibold= @random_reminder.message

app/views/dashboard/_recoveries.html.haml
= link_to recoveries_path do
  %article.px-3.py-2.rounded-md.border.border-2.border-neutral-300.bg-white.hover:bg-neutral-50.hover:border-neutral-500
    .flex.justify-between.items-center.px-3
      %h3.text-xl.font-bold Recoveries
      %p.text-3xl.text-blue-500.font-bold.number= recoveries.size

app/views/dashboard/_recoveries_count.html.haml
= link_to recoveries_path, title: "Recoveries" do
  %article.px-3.py-2.rounded-md.border.border-2.border-neutral-300.bg-white.hover:bg-neutral-50.hover:border-neutral-500
    .flex.justify-between.items-center.px-3
      .flex.items-center
        = image_tag "leaf.svg", alt: "leaf", class: "w-6 mr-3"
        %h3.text-xl.font-bold Recoveries
      %p.text-3xl.text-blue-500.font-bold.number= recoveries_count

app/views/dashboard/_reminders_count.html.haml
= link_to reminders_path, title: "Reminders" do
  %article.px-3.py-2.rounded-md.border.border-2.border-neutral-300.bg-white.hover:bg-neutral-50.hover:border-neutral-500
    .flex.justify-between.items-center.px-3
      .flex.items-center
        = image_tag "flower.svg", alt: "leaf", class: "w-6 mr-3"
        %h3.text-xl.font-bold Reminders
      %p.text-3xl.text-blue-500.font-bold.number= reminders_count

app/views/dashboard/_routines_count.html.haml
= link_to routines_path, title: "Routines" do
  %article.px-3.py-2.rounded-md.border.border-2.border-neutral-300.bg-white.hover:bg-neutral-50.hover:border-neutral-500
    .flex.justify-between.items-center.px-3
      .flex.items-center
        = image_tag "clock.svg", alt: "routines", class: "w-6 mr-3"
        %h3.text-xl.font-bold Routines
      %p.text-3xl.text-blue-500.font-bold.number= routines_count

app/views/dashboard/_thoughts_count.html.haml
= link_to thoughts_path, title: "Thoughts" do
  %article.px-3.py-2.rounded-md.border.border-2.border-neutral-300.bg-white.hover:bg-neutral-50.hover:border-neutral-500
    .flex.justify-between.items-center.px-3
      .flex.items-center
        = image_tag "notebook.svg", alt: "notebook", class: "w-6 mr-3"
        %h3.text-xl.font-bold Thoughts
      %p.text-3xl.text-blue-500.font-bold.number= thoughts_count

app/views/dashboard/index.html.haml
.mt-3.mb-5
  %h2.text-2xl.font-bold Dashboard
- if @reminders_count.positive?
  .my-5
    = render "random_reminder"
  %hr.my-8
%nav
  %ul.grid.grid-cols-1.gap-y-5.md:grid-cols-2.md:gap-5.xl:grid-cols-3
    %li
      = render "reminders_count", reminders_count: @reminders_count
    %li
      = render "thoughts_count", thoughts_count: @thoughts_count
    %li
      = render "recoveries_count", recoveries_count: @recoveries_count
    %li
      = render "routines_count", routines_count: @routines_count
    %li
      = render "budgets_count", budgets_count: @budgets_count