config/routes.rb
Rails.application.routes.draw do
  root 'dashboard#index'

  # Devise
  devise_for :users, skip: [:registrations]

  # Users
  get 'users/account', to: 'users#account'

  # Dashboard
  resources :dashboard, only: %i[index]

  # Thoughts
  get 'thoughts/favorites', to: 'thoughts#favorites'
  patch 'thoughts/:id/bookmark', to: 'thoughts#bookmark'
  patch 'thoughts/:id/unbookmark', to: 'thoughts#unbookmark'
  delete 'thoughts/all', to: 'thoughts#destroy_all'
  resources :thoughts, only: %i[index new edit create destroy update]

  # Recoveries
  get 'recoveries/favorites', to: 'recoveries#favorites'
  delete 'recoveries/all', to: 'recoveries#destroy_all'
  resources :recoveries
  patch 'recoveries/:id/report', to: 'recoveries#submit_report'
  get 'recoveries/:id/renew', to: 'recoveries#renew'
  patch 'recoveries/:id/renew', to: 'recoveries#submit_renew'
  patch 'recoveries/:id/bookmark', to: 'recoveries#bookmark'
  patch 'recoveries/:id/unbookmark', to: 'recoveries#unbookmark'

  # Stoppers
  resources :recoveries do
    resources :stoppers, only: %i[index new create]
  end

  # Routines
  get 'routines/favorites', to: 'routines#favorites'
  delete 'routines/all', to: 'routines#destroy_all'
  resources :routines
  patch 'routines/:id/report', to: 'routines#submit_report'
  patch 'routines/:id/setback', to: 'routines#submit_setback'
  patch 'routines/:id/bookmark', to: 'routines#bookmark'
  patch 'routines/:id/unbookmark', to: 'routines#unbookmark'
  get 'routines/:id/new_target', to: 'routines#new_target'
  patch 'routines/:id/submit_new_target', to: 'routines#submit_new_target'

  # Reminders
  delete 'reminders/all', to: 'reminders#destroy_all'
  resources :reminders

  # Budgets
  resources :budgets

  # Expenses
  resources :budgets do
    resources :expenses, except: %i[index]
  end
end

app/models/recovery.rb
# == Schema Information
#
# Table name: recoveries
#
#  id             :bigint           not null, primary key
#  bookmarked     :boolean          default(FALSE), not null
#  completed      :boolean          default(FALSE), not null
#  current_record :integer          default(0), not null
#  description    :text
#  max_record     :integer          default(0), not null
#  report_dates   :jsonb            not null
#  start_date     :date             not null
#  target_date    :date             not null
#  target_days    :integer          not null
#  title          :string           not null
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  user_id        :bigint           not null
#
# Indexes
#
#  index_recoveries_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Recovery < ApplicationRecord
  belongs_to :user
  has_many :awards, as: :awardable, dependent: :nullify
  has_many :stoppers, dependent: :destroy

  validates :title, presence: true, length: { maximum: 50 }
  validates :description, length: { maximum: 500 }
  validates :start_date, :target_date, presence: true
  validate :validate_dates, on: :create

  before_create :calculate_target_days
  before_update :calculate_target_days

  def bookmarked?
    bookmarked
  end

  def completed?
    completed
  end

  private

  def calculate_target_days
    self.target_days = (target_date - start_date).to_i + 1
  end

  def validate_dates
    return if target_date.nil? || start_date.nil?

    errors.add(:start_date, 'must be greater than the target date') if target_date < start_date
    errors.add(:start_date, 'must be from today onwards') if start_date < Time.zone.now.to_date
  end
end

app/controllers/recoveries_controller.rb
class RecoveriesController < ApplicationController
  before_action :set_recovery, only: %i[show destroy edit update submit_report renew submit_renew bookmark unbookmark]
  before_action :recovery_params, only: %i[create]
  before_action :recovery_renew_params, only: %i[submit_renew]
  before_action :set_current_date, only: %i[show submit_report favorites]
  before_action :recovery_update_params, only: %i[update]

  include Awards
  include RecoveryHelper

  def index
    @recoveries = current_user.recoveries.order(created_at: :desc)
    @bookmarked_recoveries_count = current_user.recoveries.where(bookmarked: true).count
  end

  def show; end

  def new
    @recovery = Recovery.new
  end

  def edit; end

  def create
    @recovery = current_user.recoveries.build(recovery_params)
    if @recovery.save
      redirect_to recovery_path(@recovery)
    else
      render :new
    end
  end

  def submit_report
    redirect_to recovery_path(@recovery) and return unless allow_submit_recovery_report?(@recovery)

    update_report
    redirect_to recovery_path(@recovery)
  end

  def renew
    redirect_to recovery_path(@recovery) and return unless @recovery.completed?
  end

  def submit_renew
    redirect_to recovery_path(@recovery) and return unless @recovery.completed?

    @recovery.update(**recovery_renew_params, current_record: 0, completed: false)
    redirect_to recovery_path(@recovery)
  end

  def update
    if @recovery.update(recovery_update_params)
      redirect_to recovery_path(@recovery)
    else
      render :edit
    end
  end

  def destroy
    if @recovery.destroy
      redirect_to recoveries_path
    else
      redirect_to recovery_path(@recovery)
    end
  end

  def bookmark
    @recovery.update(bookmarked: true)

    redirect_to recovery_path(@recovery)
  end

  def unbookmark
    @recovery.update(bookmarked: false)
    redirect_to recovery_path(@recovery)
  end

  def favorites
    @recoveries = current_user.recoveries.where(bookmarked: true).order(created_at: :desc)
  end

  def destroy_all
    current_user.recoveries.destroy_all
    redirect_to users_account_path
  end

  private

  def update_report
    max_record = @recovery.max_record
    current_record_plus = @recovery.current_record + 1
    completed = current_record_plus == @recovery.target_days
    @recovery.update(
      report_dates: @recovery.report_dates.push(Time.zone.now),
      max_record: [current_record_plus, max_record].max,
      current_record: current_record_plus,
      completed:
    )

    return unless completed

    tier = calculate_tier(@recovery.target_days)
    Award.create(
      user: current_user,
      title: "Completed recovery: #{@recovery.title}",
      awardable: @recovery,
      tier:
    )
  end

  def recovery_params
    params.require(:recovery).permit(:title, :description, :start_date, :target_date)
  end

  def recovery_update_params
    params.require(:recovery).permit(:title, :description)
  end

  def set_recovery
    @recovery = Recovery.find(params[:id])
  end

  def recovery_renew_params
    params.require(:recovery).permit(:start_date, :target_date)
  end

  def set_current_date
    @current_date = Time.zone.now.to_date
  end
end

app/helpers/recovery_helper.rb
module RecoveryHelper
  def allow_submit_recovery_report?(recovery)
    current_date = Time.zone.now.to_date
    current_time = Time.zone.now
    last_report = recovery.report_dates.last&.to_date

    return false unless current_time.hour >= 22 && current_time.hour <= 23

    return false if recovery.completed?

    return false unless current_date >= recovery.start_date

    return true if last_report.nil?

    return false unless current_date > last_report

    true
  end

  def calculate_progress(recovery)
    recovery.target_days.zero? ? 0.0 : (100.0 * recovery.current_record.to_f) / recovery.target_days.to_f
  end
end

app/views/recoveries/_edit_form.html.haml
- unless @recovery.errors.messages.empty?
  %p.text-xl.font-bold Errors:
  %ul.mb-5
    - @recovery.errors.messages.each_pair do |k, v|
      %li.text-rose-600= "#{k.to_s.humanize} #{v.join(',')}"
= form_for @recovery do |f|
  .form-group
    = f.label :title
    = f.text_field :title
  .form-group
    = f.label :description
    = f.text_area :description
  .form-actions
    = f.submit "Submit"

app/views/recoveries/_form.html.haml
- unless @recovery.errors.messages.empty?
  %p.text-xl.font-bold Errors:
  %ul.mb-5
    - @recovery.errors.messages.each_pair do |k, v|
      %li.text-rose-600= "#{k.to_s.humanize} #{v.join(',')}"
= form_for @recovery do |f|
  .form-group
    = f.label :title
    = f.text_field :title
  .form-group
    = f.label :description
    = f.text_area :description
  .form-group
    = f.label :start_date
    = f.date_field :start_date
  .form-group
    = f.label :target_date
    = f.date_field :target_date
  .form-actions
    = f.submit "Submit"

app/views/recoveries/_progress_bar.html.haml
.bg-neutral-300.border.border-1.border-neutral-400.leading-none.rounded-md
    .bg-green-500.leading-none.rounded-md.text-transparent{ style: "width: #{progress}%;", title: "#{progress}%" } *

app/views/recoveries/_recovery.html.haml
- progress = calculate_progress(recovery)
= link_to recovery_path(recovery), class: "block max-w-sm" do
  %article.pl-5.py-5.rounded-md.border.border-2.border-neutral-300.bg-white.hover:bg-neutral-50.hover:border-neutral-500
    .flex.items-center
      - if recovery.bookmarked?
        = image_tag "filled_heart.svg", alt: "bookmarked", class: "mr-3 w-5"
      %h3.text-xl.font-bold= recovery.title
    .mb-2.mr-3.max-w-sm.flex.items-center.justify-end
      %span.text-xs Days
    .pr-5
      .max-w-sm.flex.items-center.justify-between
        %p Target:
        %strong.number.text-xl.text-yellow-500= recovery.target_days
      .max-w-sm.flex.items-center.justify-between
        %p Max record:
        %strong.number.text-xl.text-green-500= recovery.max_record
      .max-w-sm.flex.items-center.justify-between
        %p Current record:
        %strong.number.text-xl.text-blue-500= recovery.current_record
      %hr.my-3
      .max-w-sm.flex.items-center.justify-between
        %p Stoppers:
        %strong.number.text-xl.text-rose-500= recovery.stoppers.count
      .mt-4
        - if recovery.completed?
          .my-3.text-center
            %p.text-xl.font-bold.text-green-500 Recovery completed!
        %span.text-sm.text-neutral-500 Progress:
        = render "progress_bar", progress:
    .mr-5.mt-5.flex.justify-end.text-sm.text-neutral-500
      %span Created on:&nbsp;
      %span.font-bold= recovery.created_at.strftime('%d %B')

app/views/recoveries/_recovery_details.html.haml
- progress = calculate_progress(recovery)
%article.pl-5.py-5.mx-auto.max-w-lg.rounded-md.border.border-2.border-neutral-300.bg-white
  .pr-5
    .flex.justify-between
      .flex
        = link_to edit_recovery_path(recovery) do
          = image_tag "pencil.svg", alt: "edit", class: "w-6 mr-3"
        - if recovery.bookmarked?
          = button_to "/recoveries/#{recovery.id}/unbookmark", method: :patch do
            = image_tag "filled_heart.svg", alt: "unbookmark", class: "w-6"
        - else
          = button_to "/recoveries/#{recovery.id}/bookmark", method: :patch do
            = image_tag "unfilled_heart.svg", alt: "bookmark", class: "w-6"
      = button_to recovery_path(recovery), method: :delete do
        = image_tag "trash_bin.svg", alt: "delete", class: "w-6"
    .mt-5
      %h3.mb-3.text-xl.font-bold= recovery.title
    - unless recovery.description.empty?
      .px-3.py-2.bg-neutral-100.rounded-md.border.border-neutral-300
        %p.break-words.text-neutral-600= recovery.description
    - if recovery.completed?
      .my-6.text-center
        %p.text-xl.font-bold.text-green-500 Recovery completed!
    .w-fit.mx-auto.mt-8.mb-5.grid.grid-cols-2.gap-10
      .text-center
        %strong Start date
        %br
        %span= recovery.start_date.strftime('%d %B')
      .text-center
        %strong Target date
        %br
        %span= recovery.target_date.strftime('%d %B')
  .mb-2.pr-3.max-w-lg.flex.items-center.justify-end
    %span.text-xs Days
  .pr-5
    .max-w-lg.flex.items-center.justify-between
      %p Target:
      %strong.number.text-xl.text-yellow-500= recovery.target_days
    .max-w-lg.flex.items-center.justify-between
      %p Max record:
      %strong.number.text-xl.text-green-500= recovery.max_record
    .max-w-lg.flex.items-center.justify-between
      %p Current record:
      %strong.number.text-xl.text-blue-500= recovery.current_record
    %hr.my-3
    .max-w-lg.flex.items-center.justify-between
      .flex.items-center
        %p.font-bold.mr-3 Stoppers:
        - if @current_date >= recovery.start_date || recovery.stoppers.last&.datetime&.to_date == @current_date
          = link_to new_recovery_stopper_path(recovery), class: "mr-3" do
            = image_tag "plus.svg", alt: "back", class: "w-6"
          = link_to recovery_stoppers_path(recovery) do
            = image_tag "magnifying_glass.svg", alt: "back", class: "w-6"
      %strong.number.text-xl.text-rose-500= recovery.stoppers.count
    .mt-4
      %span.text-sm.text-neutral-500 Progress:
      = render "progress_bar", progress:
    - if allow_submit_recovery_report?(recovery)
      .mt-5
        = button_to "Submit report", "/recoveries/#{recovery.id}/report", method: :patch, class: "button bg-blue"
    - if recovery.completed?
      .mt-5.flex.items-center.justify-end
        = link_to "Renew", "/recoveries/#{recovery.id}/renew", class: "button bg-blue"
  .mr-5.mt-5.flex.justify-end.text-sm.text-neutral-500
    %span Created on:&nbsp;
    %span.font-bold= recovery.created_at.strftime('%d %B')

app/views/recoveries/_renew_form.html.haml
- unless @recovery.errors.messages.empty?
  %p.text-xl.font-bold Errors:
  %ul.mb-5
    - @recovery.errors.messages.each_pair do |k, v|
      %li.text-rose-600= "#{k.to_s.humanize} #{v.join(',')}"
= form_for @recovery, url: "/recoveries/#{@recovery.id}/renew", method: :patch do |f|
  .form-group
    = f.label :start_date
    = f.date_field :start_date
  .form-group
    = f.label :target_date
    = f.date_field :target_date
  .form-actions
    = f.submit "Submit"

app/views/recoveries/edit.html.haml
.mx-auto.max-w-xl.mt-3.mb-5
  .flex.items-center
    = link_to recovery_path(@recovery), class: "block mr-3" do
      = image_tag "arrow.svg", alt: "back", class: "w-8"
    %h2.text-2xl.font-bold Edit recovery
.max-w-xl.mx-auto
  = render "edit_form"

app/views/recoveries/favorites.html.haml
.mt-3.mb-5
  .flex.items-center
    = link_to recoveries_path, class: "block mr-3" do
      = image_tag "arrow.svg", alt: "back", class: "w-8"
    %h2.text-2xl.font-bold Recoveries
    = link_to new_recovery_path, class: "block ml-3" do
      = image_tag "plus.svg", alt: "back", class: "w-8"
%ul.grid.grid-cols-1.gap-y-5.md:grid-cols-2.md:gap-5.xl:grid-cols-3
  - @recoveries.each do |recovery|
    %li= render "recovery_details", recovery:

app/views/recoveries/index.html.haml
.mt-3.mb-5
  .flex.items-center
    = link_to root_path, class: "block mr-3" do
      = image_tag "arrow.svg", alt: "back", class: "w-8"
    %h2.text-2xl.font-bold Recoveries
    = link_to new_recovery_path, class: "block ml-3" do
      = image_tag "plus.svg", alt: "back", class: "w-8"
= link_to recoveries_favorites_path do
  %ul.my-10.grid.grid-cols-1.gap-y-5.md:grid-cols-2.md:gap-5.xl:grid-cols-3
    %li
      %article.px-3.py-2.rounded-md.border.border-2.border-neutral-300.bg-white.hover:bg-neutral-50.hover:border-neutral-500
        .flex.justify-between.items-center.px-3
          .flex.items-center
            = image_tag "filled_heart.svg", alt: "favorites", class: "w-6 mr-3"
            %h3.text-xl.font-bold Favorite recoveries
          %p.text-3xl.text-blue-500.font-bold.number= @bookmarked_recoveries_count
%ul.grid.grid-cols-1.gap-y-5.md:grid-cols-2.md:gap-5.xl:grid-cols-3
  - @recoveries.each do |recovery|
    %li= render "recovery", recovery:

app/views/recoveries/new.html.haml
.mx-auto.max-w-xl.mt-3.mb-5
  .flex.items-center
    = link_to recoveries_path, class: "block mr-3" do
      = image_tag "arrow.svg", alt: "back", class: "w-8"
    %h2.text-2xl.font-bold New recovery
.max-w-xl.mx-auto
  = render "form"

app/views/recoveries/renew.html.haml
.mx-auto.max-w-xl.mt-3.mb-5
  .flex.items-center
    = link_to recoveries_path, class: "block mr-3" do
      = image_tag "arrow.svg", alt: "back", class: "w-8"
    %h2.text-2xl.font-bold New recovery
.max-w-xl.mx-auto
  = render "renew_form"

app/views/recoveries/show.html.haml
.mx-auto.max-w-lg.mt-3.mb-5
  .flex.items-center
    = link_to recoveries_path, class: "block mr-3" do
      = image_tag "arrow.svg", alt: "back", class: "w-8"
    %h2.text-2xl.font-bold Recovery
= render "recovery_details", recovery: @recovery