config/routes.rb
Rails.application.routes.draw do
  root 'dashboard#index'

  # Devise
  devise_for :users, skip: [:registrations]

  # Users
  get 'users/account', to: 'users#account'

  # Dashboard
  resources :dashboard, only: %i[index]

  # Thoughts
  get 'thoughts/favorites', to: 'thoughts#favorites'
  patch 'thoughts/:id/bookmark', to: 'thoughts#bookmark'
  patch 'thoughts/:id/unbookmark', to: 'thoughts#unbookmark'
  delete 'thoughts/all', to: 'thoughts#destroy_all'
  resources :thoughts, only: %i[index new edit create destroy update]

  # Recoveries
  get 'recoveries/favorites', to: 'recoveries#favorites'
  delete 'recoveries/all', to: 'recoveries#destroy_all'
  resources :recoveries
  patch 'recoveries/:id/report', to: 'recoveries#submit_report'
  get 'recoveries/:id/renew', to: 'recoveries#renew'
  patch 'recoveries/:id/renew', to: 'recoveries#submit_renew'
  patch 'recoveries/:id/bookmark', to: 'recoveries#bookmark'
  patch 'recoveries/:id/unbookmark', to: 'recoveries#unbookmark'

  # Stoppers
  resources :recoveries do
    resources :stoppers, only: %i[index new create]
  end

  # Routines
  get 'routines/favorites', to: 'routines#favorites'
  delete 'routines/all', to: 'routines#destroy_all'
  resources :routines
  patch 'routines/:id/report', to: 'routines#submit_report'
  patch 'routines/:id/setback', to: 'routines#submit_setback'
  patch 'routines/:id/bookmark', to: 'routines#bookmark'
  patch 'routines/:id/unbookmark', to: 'routines#unbookmark'
  get 'routines/:id/new_target', to: 'routines#new_target'
  patch 'routines/:id/submit_new_target', to: 'routines#submit_new_target'

  # Reminders
  delete 'reminders/all', to: 'reminders#destroy_all'
  resources :reminders

  # Budgets
  resources :budgets

  # Expenses
  resources :budgets do
    resources :expenses, except: %i[index]
  end
end

app/models/reminder.rb
# == Schema Information
#
# Table name: reminders
#
#  id         :bigint           not null, primary key
#  message    :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_reminders_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Reminder < ApplicationRecord
  belongs_to :user

  validates :message, presence: true, length: { maximum: 100 }
end

app/controllers/reminders_controller.rb
class RemindersController < ApplicationController
  before_action :set_reminder, only: %i[edit update destroy show]
  before_action :reminder_params, only: %i[create]

  def index
    @reminders = current_user.reminders.order('RANDOM()')
  end

  def show; end

  def new
    @reminder = Reminder.new
  end

  def edit; end

  def create
    @reminder = current_user.reminders.build(reminder_params)
    if @reminder.save
      redirect_to reminders_path
    else
      render :new
    end
  end

  def update
    if @reminder.update(reminder_params)
      redirect_to reminders_path
    else
      render :new
    end
  end

  def destroy
    @reminder.destroy
    redirect_to reminders_path
  end

  def destroy_all
    current_user.reminders.destroy_all
    redirect_to users_account_path
  end

  private

  def set_reminder
    @reminder = Reminder.find(params[:id])
  end

  def reminder_params
    params.require(:reminder).permit(:message)
  end
end

app/views/reminders/_form.html.haml
- unless @reminder.errors.messages.empty?
  %p.text-xl.font-bold Errors:
  %ul.mb-5
    - @reminder.errors.messages.each_pair do |k, v|
      %li.text-rose-600= "#{k.to_s.humanize} #{v.join(',')}"
= form_for [@recovery, @reminder] do |f|
  .form-group
    = f.label :message
    = f.text_area :message
  .form-actions
    = f.submit "Submit"

app/views/reminders/_reminder.html.haml
= link_to reminder_path(reminder) do
  .px-3.py-2.bg-neutral-100.rounded-md.border.border-neutral-300.hover:bg-neutral-200
    %p.break-words.text-neutral-600.font-semibold= reminder.message

app/views/reminders/_reminder_details.html.haml
%article.p-5.py-5.mx-auto.max-w-lg.rounded-md.border.border-2.border-neutral-300.bg-white
  .mb-5.flex.justify-between
    = link_to edit_reminder_path(reminder) do
      = image_tag "pencil.svg", alt: "back", class: "w-6 mr-3"
    = button_to reminder_path(reminder), method: :delete do
      = image_tag "trash_bin.svg", alt: "delete", class: "w-6"
  .px-3.py-2.bg-neutral-100.rounded-md.border.border-neutral-300
    %p.break-words.text-neutral-600.font-semibold= reminder.message
    %hr.my-3
    .flex.justify-end
      .leading-none
        %span.text-sm.text-neutral-500= reminder.created_at.strftime('%A, %d %B')

app/views/reminders/edit.html.haml
.mx-auto.max-w-xl.mt-3.mb-5
  .flex.items-center
    = link_to reminders_path, class: "block mr-3" do
      = image_tag "arrow.svg", alt: "back", class: "w-8"
    %h2.text-2xl.font-bold Edit reminder
.max-w-xl.mx-auto
  = render "form"

app/views/reminders/index.html.haml
.mt-3.mb-5
  .flex.items-center
    = link_to root_path, class: "block mr-3" do
      = image_tag "arrow.svg", alt: "back", class: "w-8"
    %h2.text-2xl.font-bold Reminders
    = link_to new_reminder_path, class: "block ml-3" do
      = image_tag "plus.svg", alt: "back", class: "w-8"
%ul.grid.grid-cols-1.gap-y-3.md:grid-cols-2.md:gap-5.xl:grid-cols-3
  - @reminders.each do |reminder|
    %li= render "reminder", reminder:

app/views/reminders/new.html.haml
.mx-auto.max-w-xl.mt-3.mb-5
  .flex.items-center
    = link_to reminders_path, class: "block mr-3" do
      = image_tag "arrow.svg", alt: "back", class: "w-8"
    %h2.text-2xl.font-bold New reminder
.max-w-xl.mx-auto
  = render "form"

app/views/reminders/show.html.haml
.mx-auto.max-w-lg.mt-3.mb-5
  .flex.items-center
    = link_to reminders_path, class: "block mr-3" do
      = image_tag "arrow.svg", alt: "back", class: "w-8"
    %h2.text-2xl.font-bold reminder
= render "reminder_details", reminder: @reminder