config/routes.rb
Rails.application.routes.draw do
  root 'dashboard#index'

  # Devise
  devise_for :users, skip: [:registrations]

  # Users
  get 'users/account', to: 'users#account'

  # Dashboard
  resources :dashboard, only: %i[index]

  # Thoughts
  get 'thoughts/favorites', to: 'thoughts#favorites'
  patch 'thoughts/:id/bookmark', to: 'thoughts#bookmark'
  patch 'thoughts/:id/unbookmark', to: 'thoughts#unbookmark'
  delete 'thoughts/all', to: 'thoughts#destroy_all'
  resources :thoughts, only: %i[index new edit create destroy update]

  # Recoveries
  get 'recoveries/favorites', to: 'recoveries#favorites'
  delete 'recoveries/all', to: 'recoveries#destroy_all'
  resources :recoveries
  patch 'recoveries/:id/report', to: 'recoveries#submit_report'
  get 'recoveries/:id/renew', to: 'recoveries#renew'
  patch 'recoveries/:id/renew', to: 'recoveries#submit_renew'
  patch 'recoveries/:id/bookmark', to: 'recoveries#bookmark'
  patch 'recoveries/:id/unbookmark', to: 'recoveries#unbookmark'

  # Stoppers
  resources :recoveries do
    resources :stoppers, only: %i[index new create]
  end

  # Routines
  get 'routines/favorites', to: 'routines#favorites'
  delete 'routines/all', to: 'routines#destroy_all'
  resources :routines
  patch 'routines/:id/report', to: 'routines#submit_report'
  patch 'routines/:id/setback', to: 'routines#submit_setback'
  patch 'routines/:id/bookmark', to: 'routines#bookmark'
  patch 'routines/:id/unbookmark', to: 'routines#unbookmark'
  get 'routines/:id/new_target', to: 'routines#new_target'
  patch 'routines/:id/submit_new_target', to: 'routines#submit_new_target'

  # Reminders
  delete 'reminders/all', to: 'reminders#destroy_all'
  resources :reminders

  # Budgets
  resources :budgets

  # Expenses
  resources :budgets do
    resources :expenses, except: %i[index]
  end
end

app/models/thought.rb
# == Schema Information
#
# Table name: thoughts
#
#  id         :bigint           not null, primary key
#  bookmarked :boolean          default(FALSE), not null
#  message    :text             not null
#  mood       :integer          default("neutral"), not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_thoughts_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Thought < ApplicationRecord
  belongs_to :user

  validates :message, presence: true, length: { maximum: 1000 }
  validates :mood, presence: true

  enum mood: Saturn::Constants::MOODS

  def bookmarked?
    bookmarked
  end
end

app/controllers/thoughts_controller.rb
class ThoughtsController < ApplicationController
  before_action :thought_params, only: %i[create update]
  before_action :set_thought, only: %i[destroy edit update bookmark unbookmark]

  def index
    @thoughts = current_user.thoughts.order(created_at: :desc).page params[:page]
    @bookmarked_thoughts_count = current_user.thoughts.where(bookmarked: true).count
  end

  def new
    @thought = Thought.new
  end

  def edit; end

  def create
    @thought = current_user.thoughts.build(thought_params)
    if @thought.save
      redirect_to thoughts_path
    else
      render :new
    end
  end

  def update
    if @thought.update(thought_params)
      redirect_to thoughts_path
    else
      render :edit
    end
  end

  def destroy
    @thought.destroy
    redirect_to thoughts_path
  end

  def bookmark
    @thought.update(bookmarked: true)

    redirect_to thoughts_path
  end

  def unbookmark
    @thought.update(bookmarked: false)

    redirect_to thoughts_path
  end

  def favorites
    @thoughts = current_user.thoughts.where(bookmarked: true).order(created_at: :desc).page params[:page]
  end

  def destroy_all
    current_user.thoughts.destroy_all
    redirect_to users_account_path
  end

  private

  def thought_params
    params.require(:thought).permit(:message, :mood)
  end

  def set_thought
    @thought = Thought.find(params[:id])
  end
end

app/views/thoughts/_form.html.haml
- unless @thought.errors.messages.empty?
  %p.text-xl.font-bold Errors:
  %ul.mb-5
    - @thought.errors.messages.each_pair do |k, v|
      %li.text-rose-600= "#{k.to_s.humanize} #{v.join(',')}"
= form_for [@recovery, @thought] do |f|
  .form-group
    = f.label :message
    = f.text_area :message
  .form-group
    = f.label :mood
    = f.select :mood, options_for_select(map_sort_moods, selected: @thought.mood)
  .form-actions
    = f.submit "Submit"

app/views/thoughts/_thought.html.haml
%article.p-5.py-5.mx-auto.max-w-lg.rounded-md.border.border-2.border-neutral-300.bg-white
  .mb-5.flex.justify-between
    .flex.items-center
      = link_to edit_thought_path(thought) do
        = image_tag "pencil.svg", alt: "back", class: "w-6 mr-3"
      - if thought.bookmarked?
        = button_to "/thoughts/#{thought.id}/unbookmark", method: :patch do
          = image_tag "filled_heart.svg", alt: "unbookmark", class: "w-6"
      - else
        = button_to "/thoughts/#{thought.id}/bookmark", method: :patch do
          = image_tag "unfilled_heart.svg", alt: "unbookmark", class: "w-6"
    = button_to thought_path(thought), method: :delete do
      = image_tag "trash_bin.svg", alt: "delete", class: "w-6"
  .px-3.py-2.bg-neutral-100.rounded-md.border.border-neutral-300
    %p.break-words.text-neutral-600.font-semibold= thought.message
    %hr.my-3
    .flex.justify-end
      .leading-none
        .text-sm
          %span This made feel
          %strong= thought.mood
        %span.text-sm.text-neutral-500= thought.created_at.strftime('%A, %d %B')

app/views/thoughts/edit.html.haml
.mx-auto.max-w-xl.mt-3.mb-5
  .flex.items-center
    = link_to thoughts_path, class: "block mr-3" do
      = image_tag "arrow.svg", alt: "back", class: "w-8"
    %h2.text-2xl.font-bold Edit thought
.max-w-xl.mx-auto
  = render "form"

app/views/thoughts/favorites.html.haml
.mt-3.mb-5
  .flex.items-center
    = link_to thoughts_path, class: "block mr-3" do
      = image_tag "arrow.svg", alt: "back", class: "w-8"
    %h2.text-2xl.font-bold Thoughts
    = link_to new_thought_path, class: "block ml-3" do
      = image_tag "plus.svg", alt: "back", class: "w-8"
%ul.grid.grid-cols-1.gap-y-5.md:grid-cols-2.md:gap-5.xl:grid-cols-3
  - @thoughts.each do |thought|
    %li= render "thought", thought:

app/views/thoughts/index.html.haml
.mt-3.mb-5
  .flex.items-center
    = link_to root_path, class: "block mr-3" do
      = image_tag "arrow.svg", alt: "back", class: "w-8"
    %h2.text-2xl.font-bold Thoughts
    = link_to new_thought_path, class: "block ml-3" do
      = image_tag "plus.svg", alt: "back", class: "w-8"
= link_to thoughts_favorites_path do
  %ul.my-10.grid.grid-cols-1.gap-y-5.md:grid-cols-2.md:gap-5.xl:grid-cols-3
    %li
      %article.px-3.py-2.rounded-md.border.border-2.border-neutral-300.bg-white.hover:bg-neutral-50.hover:border-neutral-500
        .flex.justify-between.items-center.px-3
          .flex.items-center
            = image_tag "filled_heart.svg", alt: "favorites", class: "w-6 mr-3"
            %h3.text-xl.font-bold Favorite thoughts
          %p.text-3xl.text-blue-500.font-bold.number= @bookmarked_thoughts_count
%ul.grid.grid-cols-1.gap-y-5.md:grid-cols-2.md:gap-5.xl:grid-cols-3
  - @thoughts.each do |thought|
    %li= render "thought", thought:

= paginate @thoughts

app/views/thoughts/new.html.haml
.mx-auto.max-w-xl.mt-3.mb-5
  .flex.items-center
    = link_to thoughts_path, class: "block mr-3" do
      = image_tag "arrow.svg", alt: "back", class: "w-8"
    %h2.text-2xl.font-bold New thought
.max-w-xl.mx-auto
  = render "form"